apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mario # nome da aplicação 
  namespace: argocd 
spec:
  project: default

  source:
    repoURL: https://github.com/fch-bsp/app-siteK8S.git
    targetRevision: HEAD
    path: k8s # monitorando de 3 em 3 minutos 
  destination: 
    server: https://kubernetes.default.svc
    namespace: app-site ## tag da aplicação 

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    # automated:
    #   selfHeal: false
    #   prune: false